# Generated by Django 3.1.2 on 2020-10-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
